### ISSUE TITLE
Please update account-configurations-v2.yaml to reflect reality

### ISSUE THREAD

**Issue by d-e-s-o** [alpacahq/user-docs#152]
The [current `account-configurations-v2.yaml`](https://github.com/alpacahq/user-docs/blob/c14e3a349cbfbcefb5a87d9078f1cf704c74a825/data/webapi/entities/account-configurations-v2.yaml) says:
```yaml
spec:
  - name: dtbp_check
    type: string
    desc: |
      `both`, `entry`, or `exit`. Controls Day Trading Margin Call (DTMC) checks.
  - name: trade_confirm_email
    type: string
    desc: |
      `all` or `none`. If `none`, emails for order fills are not sent.
  - name: suspend_trade
    type: bool
    desc: If true, new orders are blocked.
  - name: no_shorting
    type: bool
    desc: If true, account becomes long-only mode.
example: |
  {
    "dtbp_check": "entry",
    "no_shorting": false,
    "suspend_trade": false,
    "trade_confirm_email": "all"
  }
```

When I query the corresponding endpoint I get back:
```json
{"dtbp_check":"entry","enable_new_position_version":true,"fractional_trading":true,"max_margin_multiplier":"4","no_shorting":false,"pdt_check":"entry","suspend_trade":false,"trade_confirm_email":"all"}
```

Why are all those additional fields not documented?
